import React from 'react'
import Contact_us from './Contact_us'
import {Link} from 'react-router-dom'
import StockPortal_navbar from './StockPortal_navbar'
function StockPortal_dashboard() {
  return (
    <div>
     <h1 className='py-3'><strong>StockPortal_dashboard</strong></h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ad mollitia harum inventore fuga rem possimus consequuntur obcaecati, debitis repellendus vitae distinctio quidem aut, autem voluptas minima odit ipsam delectus! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam delectus natus ut ducimus enim officia sequi, quam quia, nisi dolorum illum culpa temporibus praesentium perferendis error veniam fuga libero! Modi? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla natus mollitia rem omnis quibusdam, quidem, saepe voluptatum praesentium eaque neque illo. Ex voluptatem quidem nemo quae repellendus sed illo necessitatibus. The vertical menu can place the left or right side of the web pages. <br /> But the default vertical menu placed on the left side. </p>
 
    </div>
  )
}

export default StockPortal_dashboard
